// src/components/NotionBlocks/NotionBlocks.svelte
<script lang="ts">
    import {NotionBlocksHtmlParser} from '@notion-stuff/blocks-html-parser/src';
    export let blocks: any;
    
    const parser = NotionBlocksHtmlParser.getInstance();
    let stringifiedHtml = ''
    $: if (blocks) {
        stringifiedHtml = parser.parse(blocks);
    }
    
</script>

<div>
    {@html stringifiedHtml}
</div>

// components/NotionBlocks/NotionBlocks.tsx
import { NotionBlocksHtmlParser } from '@notion-stuff/blocks-html-parser/src';
import { BlockObjectResponse, ListBlockChildrenResponse, PartialBlockObjectResponse } from '@notionhq/client/build/src/api-endpoints';

const parser = NotionBlocksHtmlParser.getInstance();

export function NotionBlocks({
    blocks
}: {blocks: (BlockObjectResponse | PartialBlockObjectResponse)[]}){
    const stringifiedHtml = parser.parse(blocks);
    return <div className="" dangerouslySetInnerHTML={{__html: stringifiedHtml}} />
}
