// components/BreadCrumbs.tsx/BreadCrumbs.tsx
import { BreadCrumbsProps } from "./types";
import styles from './BreadCrumbs.module.css'
import Link from "next/link";
import * as Separator from '@radix-ui/react-separator';
import { ParentBreadcrumbSpec } from "../../utils/NotionClient";

export function BreadCrumbs({
    showHome=true,
    steps
}: BreadCrumbsProps) {
  return <div className="d-flex">
    {showHome && <BreadCrumbStep step={{type:null, id:"", name: "Home"}} />}
    {steps.map(step => <BreadCrumbStep step={step} />)}
  </div>;
}

function BreadCrumbStep({
    step
}: {step: ParentBreadcrumbSpec}){
    const {type, id, name} = step;
    const url = type && id ? `/${type}/${id}` : "/"
    return <div className="d-flex">
        <Link href={url}>{name}</Link>
        <hr className="vr mx-2"/>
    </div>
}

// src/components/Breadcrumbs.svelte
<script lang="ts">
	import type { ParentBreadcrumbSpec } from 'src/utils/NotionClient';
	import { Breadcrumb, BreadcrumbItem } from 'sveltestrap';
	export let steps: ParentBreadcrumbSpec[];
	export let showHome: boolean = true;
</script>

<Breadcrumb class="pt-4">
	{#if showHome}
		<BreadcrumbItem>
			<a href="/">Home</a>
		</BreadcrumbItem>
	{/if}
	{#each steps as step}
		<BreadcrumbItem>
			<a href={`/${step.type}/${step.id}`}>{step.name}</a>
		</BreadcrumbItem>
	{/each}
</Breadcrumb>

<Breadcrumb />
